version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
      - .secrets
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"